//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBManufacturing.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalDic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalDic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCBManufacturing.Resources.Localization.LocalDic", typeof(LocalDic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board preferences.
        /// </summary>
        public static string Board_preferences {
            get {
                return ResourceManager.GetString("Board preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board thickness.
        /// </summary>
        public static string Board_thickness {
            get {
                return ResourceManager.GetString("Board thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose manufacturing options for your PCB..
        /// </summary>
        public static string Choose_manufacturing_options_for_your_PCB {
            get {
                return ResourceManager.GetString("Choose manufacturing options for your PCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string Dark_theme {
            get {
                return ResourceManager.GetString("Dark theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabrication.
        /// </summary>
        public static string Fabrication {
            get {
                return ResourceManager.GetString("Fabrication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish type.
        /// </summary>
        public static string Finish_type {
            get {
                return ResourceManager.GetString("Finish type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order.
        /// </summary>
        public static string Invalid_order {
            get {
                return ResourceManager.GetString("Invalid order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer count.
        /// </summary>
        public static string Layer_count {
            get {
                return ResourceManager.GetString("Layer count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string LayerFew {
            get {
                return ResourceManager.GetString("LayerFew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string LayerMany {
            get {
                return ResourceManager.GetString("LayerMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layers.
        /// </summary>
        public static string Layers {
            get {
                return ResourceManager.GetString("Layers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order placed.
        /// </summary>
        public static string Order_placed {
            get {
                return ResourceManager.GetString("Order placed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order summary.
        /// </summary>
        public static string Order_summary {
            get {
                return ResourceManager.GetString("Order summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCB Manufacturing.
        /// </summary>
        public static string PCB_Manufacturing {
            get {
                return ResourceManager.GetString("PCB Manufacturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCB Preview.
        /// </summary>
        public static string PCB_Preview {
            get {
                return ResourceManager.GetString("PCB Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        public static string Place_Order {
            get {
                return ResourceManager.GetString("Place Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all required PCB configuration fields before placing the order..
        /// </summary>
        public static string Please_complete_all_required_PCB_configuration_fields_before_placing_the_order_ {
            get {
                return ResourceManager.GetString("Please complete all required PCB configuration fields before placing the order.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode is required..
        /// </summary>
        public static string Postcode_is_required {
            get {
                return ResourceManager.GetString("Postcode is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode must contain 4 to 10 digits..
        /// </summary>
        public static string Postcode_must_contain_4_to_10_digits {
            get {
                return ResourceManager.GetString("Postcode must contain 4 to 10 digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price modifier.
        /// </summary>
        public static string Price_modifier {
            get {
                return ResourceManager.GetString("Price modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production time.
        /// </summary>
        public static string Production_time {
            get {
                return ResourceManager.GetString("Production time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to order.
        /// </summary>
        public static string Ready_to_order {
            get {
                return ResourceManager.GetString("Ready to order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the PCB configuration before placing the order..
        /// </summary>
        public static string Review_the_PCB_configuration_before_placing_the_order {
            get {
                return ResourceManager.GetString("Review the PCB configuration before placing the order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solder mask.
        /// </summary>
        public static string Solder_mask {
            get {
                return ResourceManager.GetString("Solder mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface finish.
        /// </summary>
        public static string Surface_finish {
            get {
                return ResourceManager.GetString("Surface finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string Total_price {
            get {
                return ResourceManager.GetString("Total price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your choices update the quote instantly..
        /// </summary>
        public static string Your_choices_update_the_quote_instantly {
            get {
                return ResourceManager.GetString("Your choices update the quote instantly", resourceCulture);
            }
        }
    }
}
