<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <ApplicationIcon>Images\pcb-board.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Themes\Colors.Dark.xam" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Localization\LocalDic.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LocalDic.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\LocalDic.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LocalDic.Designer.cs</LastGenOutput>
      <CustomToolNamespace>PCBManufacturing.Resources.Localization</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Localization\LocalDic.ru.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <CustomToolNamespace>PCBManufacturing.Resources.Localization</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
